name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    env: 
      UNIT_TESTS_PROJECT_PATH: ./Demo/tests/Demo.UnitTests/Demo.UnitTests/Demo.Tests.csproj
      WEBAPI_SOLUTION_PATH: ./Demo/Demo.sln

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
        
    - name: Executing Tests - Unit and Integration
      run: dotnet test ${{ env.UNIT_TESTS_PROJECT_PATH }} --verbosity minimal        
        
    - name: Install dependencies
      run: dotnet restore ${{ env.WEBAPI_SOLUTION_PATH }}
      
    - name: Building Solution
      run: dotnet build ${{ env.WEBAPI_SOLUTION_PATH }} --configuration Release
